# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A11Y Rocks
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on Web Accessibility
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://a11y.rocks" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
exclude: ['node_modules', 'package.json', 'gulpfile.js', 'src', '.DS_Store', '.sass-cache', 'README.md', 'npm-debug.log', 'LICENSE', 'deploy.js']

markdown: kramdown
permalink: pretty

compress_html:
  clippings: all

authors:
  diessica:
    name: Diéssica Gurskas
    email: diessicode@gmail.com
    web: https://diessi.ca
    twitter: diessicode
    github: diessica
    picture: https://avatars3.githubusercontent.com/u/5303585?v=3&s=200
  lucas:
    name: Lucas da Silva
    email: lucas@lucas.ninja
    web: https://lucas.ninja
    twitter: _agtlucas
    github: agtlucas
    picture: https://avatars0.githubusercontent.com/u/1909761?v=3&s=200
